spring: 
    application:
        name: catalog
    datasource:
        name: dsource
        url: jdbc:mysql://localhost:3306/avadb
        username: root
        password: P@ssmysql
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        properties:
            hibernate: 
                dilect: org.hibernate.dialect.MySQL55Dialect.MySQL55Dialect
        hibernate:
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

server: 
    port: 8082